import os
import requests
from flask import Flask, request, jsonify
from openai import OpenAI

app = Flask(__name__)

# -----------------------------
# Groq Configuration
# -----------------------------
client = OpenAI(
    api_key=os.environ["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1"
)

VERIFY_TOKEN = "edubot_verify"


# -----------------------------
# Home
# -----------------------------
@app.route("/")
def home():
    return "EduBot is running successfully!"


# -----------------------------
# Privacy Policy
# -----------------------------
@app.route("/privacy-policy")
def privacy_policy():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>EduBot Privacy Policy</title>
    </head>
    <body>

    <h1>EduBot Privacy Policy</h1>

    <p>
    EduBot respects your privacy and protects your personal information.
    </p>

    <h2>Information We Use</h2>
    <p>
    EduBot uses Instagram messaging data only to provide
    AI-powered homework assistance and replies.
    </p>

    <h2>Data Usage</h2>
    <p>
    Messages are used only to generate helpful AI responses.
    </p>

    <h2>Data Sharing</h2>
    <p>
    We do not sell, rent, or share personal information with third parties.
    </p>

    <h2>Contact</h2>
    <p>
    Email: zedex_editingz@gmail.com
    </p>

    </body>
    </html>
    """


# -----------------------------
# User Data Deletion
# -----------------------------
@app.route("/data-deletion")
def data_deletion():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>EduBot Data Deletion</title>
    </head>
    <body>

    <h1>User Data Deletion</h1>

    <p>
    Users can request deletion of their data from EduBot.
    </p>

    <p>
    Please contact us with your Instagram username.
    </p>

    <p>
    We will review your request and delete applicable data.
    </p>

    <p>
    Email: zedex_editingz@gmail.com
    </p>

    </body>
    </html>
    """


# -----------------------------
# Terms of Service
# -----------------------------
@app.route("/terms")
def terms():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>EduBot Terms of Service</title>
    </head>
    <body>

    <h1>EduBot Terms of Service</h1>

    <p>
    Welcome to EduBot. By using this service, you agree to these Terms of Service.
    </p>

    <h2>Educational Purpose</h2>
    <p>
    EduBot provides AI-powered educational assistance and homework support.
    </p>

    <h2>AI Responses</h2>
    <p>
    Responses are generated by artificial intelligence and may not always be accurate. Users should verify important information independently.
    </p>

    <h2>Acceptable Use</h2>
    <p>
    Users must not use EduBot for illegal, abusive, harmful, or unauthorized purposes.
    </p>

    <h2>Privacy</h2>
    <p>
    Your use of EduBot is also governed by our Privacy Policy.
    </p>

    <h2>Contact</h2>
    <p>
    Email: zedex_editingz@gmail.com
    </p>

    </body>
    </html>
    """


# -----------------------------
# Meta Webhook Verification
# -----------------------------
@app.route("/webhook", methods=["GET"])
def verify():

    mode = request.args.get("hub.mode")
    token = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")

    if mode == "subscribe" and token == VERIFY_TOKEN:
        return challenge, 200

    return "Verification failed", 403


# -----------------------------
# Send Instagram Reply
# -----------------------------
def send_instagram_message(recipient_id, message_text):

    access_token = os.environ["INSTAGRAM_ACCESS_TOKEN"]

    url = "https://graph.instagram.com/v23.0/me/messages"

    payload = {
        "recipient": {
            "id": recipient_id
        },
        "message": {
            "text": message_text
        }
    }

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json"
    }

    response = requests.post(
        url,
        json=payload,
        headers=headers
    )

    print("Instagram Reply:", response.text)
    # -----------------------------
# Receive Instagram Messages
# -----------------------------
@app.route("/webhook", methods=["POST"])
def webhook():

    try:
        data = request.get_json()

        print("========== WEBHOOK RECEIVED ==========")
        print(data)
        print("======================================")

        entry = data["entry"][0]
        messaging = entry["messaging"][0]

        sender_id = messaging["sender"]["id"]

        user_message = (
            messaging
            .get("message", {})
            .get("text", "")
        )

        if user_message:

            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are EduBot, an AI homework tutor. "
                            "Explain answers step by step using simple language."
                        )
                    },
                    {
                        "role": "user",
                        "content": user_message
                    }
                ],
                temperature=0.5,
                max_tokens=800
            )

            ai_reply = response.choices[0].message.content

            send_instagram_message(
                sender_id,
                ai_reply
            )

        return "EVENT_RECEIVED", 200


    except Exception as e:
        print("ERROR:", e)
        return "ERROR", 500



# -----------------------------
# AI Endpoint
# -----------------------------
@app.route("/ask", methods=["POST"])
def ask():

    try:

        data = request.get_json()

        if not data or "question" not in data:
            return jsonify({
                "error": "Question is required"
            }), 400


        question = data["question"]


        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are EduBot, an AI homework tutor. "
                        "Explain answers step by step using simple language."
                    )
                },
                {
                    "role": "user",
                    "content": question
                }
            ],
            temperature=0.5,
            max_tokens=800
        )


        return jsonify({
            "success": True,
            "answer": response.choices[0].message.content
        })


    except Exception as e:

        return jsonify({
            "success": False,
            "error": str(e)
        }), 500



# -----------------------------
# Instagram Business Login Callback
# -----------------------------
@app.route("/auth/instagram/callback")
def instagram_callback():

    return "Instagram login successful"



# -----------------------------
# Run Flask
# -----------------------------
if __name__ == "__main__":

    port = int(os.environ.get("PORT", 10000))

    app.run(
        host="0.0.0.0",
        port=port
    )
