services:
  - type: web
    name: classmate-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: PYTHON_VERSION
        value: 3.11.9
